services:
  ai_middleware:
    build: ../ai_middleware
    container_name: ai_middleware
    ports:
      - "9006:9006"
    environment:
      MODULE_NAME: main
      VARIABLE_NAME: app
      PORT: 9006
    volumes:
      - ../memory:/memory
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
