version: '3.8'
services:
  ai-middleware:
    build:
      context: ../ai-middleware
      dockerfile: Dockerfile
    ports:
      - "9006:80"
    volumes:
      - ../ai-middleware:/app/ai-middleware:cached
      - ../web-ui/dist:/app/ui:cached
      - ../memory:/memory:cached
    env_file:
      - .env

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
